FROM node:24.14-alpine
WORKDIR /app
COPY package*.json ./

RUN npm install

COPY . .

ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_SUPABASE_HOST_NAME
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

# Public
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_SUPABASE_HOST_NAME=$NEXT_PUBLIC_SUPABASE_HOST_NAME
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

# Secret
ENV CLERK_SECRET_KEY="sk_test_dummy"
ENV CLERK_WEBHOOK_SIGNING_SECRET="whsec_dummy"
ENV DATABASE_URL="postgresql://dummy_user:dummy_password@localhost:5432/dummy_db"
ENV DIRECT_URL="postgresql://dummy_user:dummy_password@localhost:5432/dummy_db"
ENV SUPABASE_SECRET_KEY="sb_secret_dummy"
ENV STRIPE_SECRET_KEY="sk_test_dummy"
ENV STRIPE_WEBHOOK_SECRET="whsec_dummy"

RUN npx prisma generate

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]