import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import AdminNavigation from '@/components/layout/navigation/AdminNavigation';
import { inter } from '../fonts';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} antialiased bg-black text-white`}>
          <AdminNavigation />
          <main className="min-h-screen max-w-275 mx-auto px-4 pt-10 pb-15">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
