import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { TooltipProvider } from '@/components/ui/tooltip';
import { inter } from '../fonts';
import MainNavigation from '@/components/layout/navigation/MainNavigation';
import Footer from '@/components/layout/footer/Footer';
import '../globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          <MainNavigation />
          <TooltipProvider>
            <main className='min-h-screen max-w-275 mx-auto px-4 pt-10 pb-15'>
              {children}
            </main>
          </TooltipProvider>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
